# Generated by Django 6.0.3 on 2026-05-01 14:19

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('properties', '0006_alter_property_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('original_listing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_reduction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('deposit_paid_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_reference', models.CharField(blank=True, max_length=255)),
                ('agent_commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('commission_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('negotiation', '🤝 Negotiation'), ('deposit', '💰 Deposit Paid'), ('contract', '📄 Contract Signed'), ('inspection', '🔍 Property Inspection'), ('closing', '🏁 Closing'), ('completed', '✅ Completed'), ('cancelled', '❌ Cancelled'), ('disputed', '⚖️ Under Dispute')], default='negotiation', max_length=20)),
                ('current_step', models.IntegerField(default=1, help_text='Current milestone step')),
                ('offer_date', models.DateTimeField(auto_now_add=True)),
                ('acceptance_date', models.DateTimeField(blank=True, null=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('possession_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('special_conditions', models.TextField(blank=True, help_text='Any special conditions agreed upon')),
                ('contingencies', models.TextField(blank=True, help_text='Sale contingencies (financing, inspection, etc.)')),
                ('deal_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_deals', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_room', to='bookings.booking')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_deals', to=settings.AUTH_USER_MODEL)),
                ('property_obj', models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='deal_rooms', to='properties.property')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('terms', models.TextField(blank=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('countered', 'Countered'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deal_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='dealroom.dealroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deal_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='dealroom.dealroom')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DealMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('general', 'General'), ('offer', 'Offer Related'), ('document', 'Document Discussion'), ('inspection', 'Inspection Discussion'), ('closing', 'Closing Discussion'), ('urgent', 'Urgent')], default='general', max_length=20)),
                ('content', models.TextField()),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='deal_attachment')),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deal_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dealroom.dealroom')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('offer_letter', '📄 Offer Letter'), ('counter_offer', '🔄 Counter Offer'), ('purchase_agreement', '✍️ Purchase Agreement'), ('title_deed', '📜 Title Deed'), ('survey_report', '🗺️ Survey Report'), ('valuation_report', '💰 Valuation Report'), ('inspection_report', '🔍 Inspection Report'), ('deposit_receipt', '💵 Deposit Receipt'), ('commission_agreement', '🤝 Commission Agreement'), ('closing_document', '🏁 Closing Document'), ('tax_document', '📊 Tax Document'), ('other', '📎 Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='deal_document')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('requires_signature', models.BooleanField(default=False)),
                ('signed_by_buyer', models.BooleanField(default=False)),
                ('signed_by_seller', models.BooleanField(default=False)),
                ('signed_by_agent', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deal_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dealroom.dealroom')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DealActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('status_change', 'Status Changed'), ('document_upload', 'Document Uploaded'), ('document_signed', 'Document Signed'), ('message_sent', 'Message Sent'), ('offer_made', 'Offer Made'), ('offer_accepted', 'Offer Accepted'), ('milestone_completed', 'Milestone Completed'), ('price_updated', 'Price Updated'), ('deposit_paid', 'Deposit Paid'), ('deal_completed', 'Deal Completed')], max_length=30)),
                ('description', models.TextField()),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deal_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='dealroom.dealroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dealroom',
            index=models.Index(fields=['status', '-created_at'], name='dealroom_de_status_e70d66_idx'),
        ),
        migrations.AddIndex(
            model_name='dealroom',
            index=models.Index(fields=['buyer', '-created_at'], name='dealroom_de_buyer_i_bc12b8_idx'),
        ),
        migrations.AddIndex(
            model_name='dealroom',
            index=models.Index(fields=['seller', '-created_at'], name='dealroom_de_seller__ae6985_idx'),
        ),
        migrations.AddIndex(
            model_name='dealroom',
            index=models.Index(fields=['deal_number'], name='dealroom_de_deal_nu_4bdda2_idx'),
        ),
    ]
