# Generated by Django 4.2.7 on 2026-04-01 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 1, 11, 1, 46, 894451, tzinfo=datetime.timezone.utc)),
        ),
    ]
