# Generated by Django 6.0.3 on 2026-05-01 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 31, 9, 53, 40, 859481, tzinfo=datetime.timezone.utc)),
        ),
    ]
