# Generated by Django 6.0.3 on 2026-05-01 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 31, 14, 19, 22, 929151, tzinfo=datetime.timezone.utc)),
        ),
    ]
