# Generated by Django 4.2.7 on 2026-04-01 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 1, 20, 44, 49, 757914, tzinfo=datetime.timezone.utc)),
        ),
    ]
