# Generated by Django 6.0.3 on 2026-05-01 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 31, 20, 29, 50, 169018, tzinfo=datetime.timezone.utc)),
        ),
    ]
