# Generated by Django 6.0.3 on 2026-04-05 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-is_boosted', '-created_at']},
        ),
        migrations.AddField(
            model_name='property',
            name='boost_level',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('vip', 'VIP')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='boost_payment_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='boost_price_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 5, 14, 55, 47, 697361, tzinfo=datetime.timezone.utc)),
        ),
    ]
