# Generated by Django 6.0.3 on 2026-04-06 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_options_property_boost_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 6, 17, 14, 23, 74737, tzinfo=datetime.timezone.utc)),
        ),
    ]
