# Generated by Django 6.0.3 on 2026-04-06 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 6, 17, 16, 36, 621659, tzinfo=datetime.timezone.utc)),
        ),
    ]
