# Generated by Django 6.0.3 on 2026-04-15 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_property_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 15, 21, 58, 33, 177090, tzinfo=datetime.timezone.utc)),
        ),
    ]
