# Generated by Django 6.0.3 on 2026-04-16 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_property_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 16, 8, 47, 36, 519691, tzinfo=datetime.timezone.utc)),
        ),
    ]
