# Generated by Django 6.0.3 on 2026-04-16 16:07

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_property_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('title_deed', 'Title Deed'), ('survey_plan', 'Survey Plan'), ('valuation_report', 'Valuation Report'), ('tax_clearance', 'Tax Clearance'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='properties/documents/%Y/%m/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('inquiry_type', models.CharField(choices=[('viewing', 'Schedule Viewing'), ('price', 'Price Inquiry'), ('negotiation', 'Price Negotiation'), ('documents', 'Document Request'), ('general', 'General Question')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('preferred_date', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='properties/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])])),
                ('video_url', models.URLField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='properties/videos/thumbnails/%Y/%m/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='agent_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='property',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='List of amenities'),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_airport',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Distance to nearest airport (km)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_city_center',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Distance to city center (km)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_highway',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Distance to main highway (km)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_hospital',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Distance to nearest hospital (km)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_mall',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Distance to nearest mall (km)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='distance_to_nearest_school',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Distance to nearest school (km)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='energy_rating',
            field=models.CharField(blank=True, help_text='Energy efficiency rating (A-G)', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-Furnished'), ('fully_furnished', 'Fully Furnished'), ('luxury', 'Luxury Furnished')], default='unfurnished', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='has_air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_backup_generator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_bbq_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_borehole',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_cable_tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_electric_fence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_fireplace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_gated_community',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_modern_kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_playground',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_security_guards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_security_lights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_solar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_study_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_terrace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_title_deed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_walk_in_closet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_water_tank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='land_registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_roads',
            field=models.CharField(blank=True, help_text='Main roads nearby (comma-separated)', max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='nearby_schools',
            field=models.TextField(blank=True, help_text='List of nearby schools (comma-separated)'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_bus_stop',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_cafe',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_gym',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_hospital',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_mall',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_market',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_park',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_pharmacy',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_restaurant',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_road',
            field=models.CharField(blank=True, help_text='Nearest main road', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_supermarket',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_taxi_stage',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_description',
            field=models.TextField(blank=True, help_text='Description of the neighborhood'),
        ),
        migrations.AddField(
            model_name='property',
            name='neighborhood_name',
            field=models.CharField(blank=True, help_text='Name of the neighborhood/area', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_spaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_type',
            field=models.CharField(choices=[('none', 'No Parking'), ('street', 'Street Parking'), ('open', 'Open Parking'), ('covered', 'Covered Parking'), ('garage', 'Garage'), ('multiple', 'Multiple Garages')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='pets_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='public_transport',
            field=models.BooleanField(default=False, help_text='Public transport available nearby'),
        ),
        migrations.AddField(
            model_name='property',
            name='school_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Area school rating (0-5)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='property',
            name='smoking_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='title_deed_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='properties/videos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])]),
        ),
        migrations.AddField(
            model_name='property',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='properties/videos/thumbnails/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='viewing_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True, help_text='360° Virtual Tour URL', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 16, 16, 7, 46, 353458, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('land', 'Land'), ('commercial', 'Commercial'), ('condo', 'Condo'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('duplex', 'Duplex'), ('bungalow', 'Bungalow')], default='house', max_length=20),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'district'], name='properties__city_bd502c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'transaction_type'], name='properties__propert_363fab_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['bedrooms', 'bathrooms'], name='properties__bedroom_446002_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='properties__created_72ecc3_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_boosted', '-created_at'], name='properties__is_boos_5bb2ea_idx'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyinquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyreview',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyvideo',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyreview',
            unique_together={('property', 'user')},
        ),
    ]
