# Generated by Django 6.0.3 on 2026-04-17 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_propertydocument_propertyinquiry_propertyreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 17, 12, 35, 26, 728434, tzinfo=datetime.timezone.utc)),
        ),
    ]
