# Generated by Django 6.0.3 on 2026-04-20 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_alter_property_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interest_rate', models.DecimalField(decimal_places=3, help_text='Annual interest rate (e.g., 0.165 for 16.5%)', max_digits=5)),
                ('max_term', models.IntegerField(help_text='Maximum loan term in years')),
                ('min_down_payment', models.DecimalField(decimal_places=3, help_text='Minimum down payment as percentage (e.g., 0.15 for 15%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['interest_rate'],
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 20, 22, 44, 53, 991674, tzinfo=datetime.timezone.utc)),
        ),
    ]
