# Generated by Django 6.0.3 on 2026-04-26 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_alter_property_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 26, 15, 21, 14, 600602, tzinfo=datetime.timezone.utc)),
        ),
    ]
