# Generated by Django 6.0.3 on 2026-04-27 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_alter_property_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 27, 11, 41, 51, 746823, tzinfo=datetime.timezone.utc)),
        ),
    ]
