# Generated by Django 6.0.3 on 2026-04-27 12:43

import datetime
import django.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_alter_property_expires_at_alter_property_video_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='building_type',
            field=models.CharField(blank=True, choices=[('detached', 'Detached'), ('semi_detached', 'Semi-Detached'), ('attached', 'Attached'), ('corner', 'Corner Unit'), ('end_unit', 'End Unit'), ('mid_rise', 'Mid-Rise Building'), ('high_rise', 'High-Rise Building'), ('low_rise', 'Low-Rise Building')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='elevator_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='events_allowed',
            field=models.BooleanField(default=True, help_text='Events/parties allowed'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_level',
            field=models.CharField(blank=True, choices=[('ground', 'Ground Floor'), ('upper', 'Upper Floor'), ('top', 'Top Floor'), ('basement', 'Basement'), ('mezzanine', 'Mezzanine')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.IntegerField(blank=True, help_text='Which floor (for apartments/offices)', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_emergency_exits',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='has_gas',
            field=models.BooleanField(default=False, help_text='Natural gas available'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_kitchenette',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_meeting_rooms',
            field=models.BooleanField(default=False, help_text='Has meeting rooms'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_pantry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='has_reception',
            field=models.BooleanField(default=False, help_text='Has reception area'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_server_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_accessible',
            field=models.BooleanField(default=True, help_text='Wheelchair accessible'),
        ),
        migrations.AddField(
            model_name='property',
            name='loading_dock',
            field=models.BooleanField(default=False, help_text='Commercial loading dock'),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_bank',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_daycare',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_fire_station',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_police_station',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='nearest_university',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_buildings',
            field=models.IntegerField(default=1, help_text='Number of buildings on property'),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_floors',
            field=models.IntegerField(default=1, help_text='Number of floors in the building'),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_meeting_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_type',
            field=models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('shared_ownership', 'Shared Ownership'), ('co_op', 'Co-operative'), ('timeshare', 'Timeshare'), ('land_lease', 'Land Lease'), ('government', 'Government Owned'), ('trust', 'Trust Ownership')], default='freehold', max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='permitted_uses',
            field=models.TextField(blank=True, help_text='Permitted business/use types'),
        ),
        migrations.AddField(
            model_name='property',
            name='power_source',
            field=models.CharField(blank=True, help_text='Power source (National, Solar, Generator)', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='property_condition',
            field=models.CharField(choices=[('new', 'New Construction'), ('excellent', 'Excellent Condition'), ('good', 'Good Condition'), ('needs_updating', 'Needs Updating'), ('needs_renovation', 'Needs Renovation'), ('fixer_upper', 'Fixer Upper'), ('under_construction', 'Under Construction'), ('shell', 'Shell Condition'), ('as_is', 'Sold As-Is'), ('repossessed', 'Repossessed'), ('heritage', 'Heritage Listed')], default='good', max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annually', 'Semi-Annually'), ('annually', 'Annually'), ('weekly', 'Weekly'), ('daily', 'Daily')], default='monthly', max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='sewage_system',
            field=models.CharField(blank=True, choices=[('septic', 'Septic Tank'), ('sewer', 'Municipal Sewer'), ('cesspool', 'Cesspool'), ('none', 'None')], default='septic', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='signage_allowed',
            field=models.BooleanField(default=True, help_text='Business signage allowed'),
        ),
        migrations.AddField(
            model_name='property',
            name='tenure_type',
            field=models.CharField(choices=[('freehold', 'Freehold'), ('leasehold', 'Leasehold'), ('mailo', 'Mailo Land'), ('customary', 'Customary'), ('kibanja', 'Kibanja'), ('permanent', 'Permanent'), ('temporary', 'Temporary')], default='freehold', max_length=30),
        ),
        migrations.AddField(
            model_name='property',
            name='total_floors',
            field=models.IntegerField(blank=True, help_text='Total floors in building', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='water_source',
            field=models.CharField(blank=True, help_text='Source of water (National, Borehole, Tank)', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='year_renovated',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AddField(
            model_name='property',
            name='zoning_type',
            field=models.CharField(blank=True, help_text='Zoning classification', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankrate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bankrate',
            name='interest_rate',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bankrate',
            name='max_term',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bankrate',
            name='min_down_payment',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='property',
            name='distance_to_airport',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='distance_to_city_center',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='distance_to_highway',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='distance_to_hospital',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='distance_to_mall',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='distance_to_nearest_school',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='energy_rating',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 27, 12, 43, 8, 399991, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-Furnished'), ('fully_furnished', 'Fully Furnished'), ('luxury', 'Luxury Furnished'), ('bare_shell', 'Bare Shell'), ('white_box', 'White Box'), ('turnkey', 'Turnkey Ready')], default='unfurnished', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='nearby_roads',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='nearby_schools',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='nearest_road',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='parking_type',
            field=models.CharField(choices=[('none', 'No Parking'), ('street', 'Street Parking'), ('open', 'Open Parking'), ('covered', 'Covered Parking'), ('garage', 'Garage'), ('multiple', 'Multiple Garages'), ('underground', 'Underground Parking'), ('valet', 'Valet Parking'), ('carport', 'Carport'), ('parking_lot', 'Designated Parking Lot'), ('parking_permit', 'Parking Permit Required')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('duplex', 'Duplex'), ('triplex', 'Triplex'), ('bungalow', 'Bungalow'), ('mansion', 'Mansion'), ('studio', 'Studio Apartment'), ('penthouse', 'Penthouse'), ('loft', 'Loft'), ('farmhouse', 'Farmhouse'), ('cottage', 'Cottage'), ('cabin', 'Cabin'), ('row_house', 'Row House'), ('office', 'Office Space'), ('retail', 'Retail Space'), ('shop', 'Shop'), ('restaurant', 'Restaurant Space'), ('cafe', 'Cafe Space'), ('hotel', 'Hotel'), ('lodge', 'Lodge'), ('warehouse', 'Warehouse'), ('factory', 'Factory/Industrial'), ('showroom', 'Showroom'), ('mall_space', 'Mall Space'), ('land', 'Land'), ('agricultural_land', 'Agricultural Land'), ('commercial_land', 'Commercial Land'), ('industrial_land', 'Industrial Land'), ('residential_land', 'Residential Land'), ('mixed_use_land', 'Mixed-Use Land'), ('farm_land', 'Farm Land'), ('ranch', 'Ranch'), ('plot', 'Building Plot'), ('school', 'School/Educational'), ('hospital', 'Hospital/Medical'), ('church', 'Church/Worship'), ('mosque', 'Mosque'), ('temple', 'Temple'), ('community_center', 'Community Center'), ('sports_facility', 'Sports Facility'), ('parking_lot', 'Parking Lot'), ('event_center', 'Event Center'), ('funeral_home', 'Funeral Home'), ('industrial', 'Industrial'), ('manufacturing', 'Manufacturing'), ('storage', 'Storage Facility'), ('cold_storage', 'Cold Storage'), ('workshop', 'Workshop'), ('mixed_use', 'Mixed Use'), ('live_work', 'Live-Work Unit')], default='house', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='public_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='school_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('shortlet', 'Shortlet'), ('lease', 'Long-term Lease'), ('auction', 'Auction'), ('foreclosure', 'Foreclosure'), ('pre_construction', 'Pre-Construction'), ('exchange', 'Property Exchange'), ('rent_to_own', 'Rent to Own'), ('commercial_lease', 'Commercial Lease')], default='sale', max_length=30),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propertyinquiry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propertylike',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propertyreview',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propertyview',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['ownership_type'], name='properties__ownersh_4ad75c_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_condition'], name='properties__propert_365e3c_idx'),
        ),
    ]
