# Generated by Django 6.0.3 on 2026-04-27 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_property_building_type_property_elevator_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 27, 13, 53, 46, 992265, tzinfo=datetime.timezone.utc)),
        ),
    ]
