# Generated by Django 6.0.3 on 2026-04-27 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_alter_property_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 27, 14, 21, 31, 862909, tzinfo=datetime.timezone.utc)),
        ),
    ]
