# Generated by Django 6.0.3 on 2026-04-30 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_alter_property_expires_at_alter_property_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 30, 9, 1, 17, 466296, tzinfo=datetime.timezone.utc)),
        ),
    ]
