# Generated by Django 6.0.3 on 2026-04-30 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_alter_property_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 30, 16, 1, 24, 120087, tzinfo=datetime.timezone.utc)),
        ),
    ]
