# Generated by Django 6.0.3 on 2026-05-01 09:53

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='FontAwesome or Material icon name', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='services_se_is_acti_32bf00_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('decoration', 'Home Decoration'), ('cleaning', 'Cleaning Services'), ('moving', 'Moving & Relocation'), ('renovation', 'Renovation'), ('furniture', 'Furniture Supply'), ('security', 'Security Systems'), ('landscaping', 'Landscaping'), ('maintenance', 'Maintenance'), ('interior_design', 'Interior Design'), ('electrical', 'Electrical Services'), ('plumbing', 'Plumbing'), ('painting', 'Painting'), ('other', 'Other')], default='other', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_unit', models.CharField(blank=True, help_text='e.g., per hour, per room, per sqm', max_length=50)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('duration', models.CharField(blank=True, help_text='e.g., 2-3 hours, 1 day', max_length=100)),
                ('provider', models.CharField(blank=True, max_length=200)),
                ('provider_phone', models.CharField(blank=True, max_length=20)),
                ('provider_email', models.EmailField(blank=True, max_length=254)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceGalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('order', models.IntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='services.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('thumbnail', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField()),
                ('address', models.TextField()),
                ('special_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='services_se_user_id_cea692_idx'), models.Index(fields=['service', '-created_at'], name='services_se_service_f49bf9_idx'), models.Index(fields=['status', 'booking_date'], name='services_se_status_6af1df_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_type', 'is_active'], name='services_se_service_0e1319_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', '-created_at'], name='services_se_categor_588a33_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_featured', 'is_active'], name='services_se_is_feat_fb2165_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['rating'], name='services_se_rating_35e83b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicegalleryimage',
            index=models.Index(fields=['service', 'order'], name='services_se_service_1e4289_idx'),
        ),
        migrations.AddIndex(
            model_name='servicegalleryimage',
            index=models.Index(fields=['is_main'], name='services_se_is_main_6b11a7_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereview',
            index=models.Index(fields=['service', '-created_at'], name='services_se_service_62d61a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereview',
            index=models.Index(fields=['rating'], name='services_se_rating_c531bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicereview',
            unique_together={('user', 'service')},
        ),
    ]
