# Generated by Django 6.0.3 on 2026-04-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('decoration', 'Home Decoration'), ('cleaning', 'Cleaning Services'), ('moving', 'Moving & Relocation'), ('renovation', 'Renovation'), ('furniture', 'Furniture Supply'), ('security', 'Security Systems'), ('landscaping', 'Landscaping'), ('maintenance', 'Maintenance'), ('interior_design', 'Interior Design'), ('electrical', 'Electrical Services'), ('plumbing', 'Plumbing'), ('painting', 'Painting'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
