# Generated by Django 6.0.3 on 2026-04-06 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='gallery',
        ),
        migrations.CreateModel(
            name='ServiceGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/')),
                ('order', models.IntegerField(default=0)),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='services.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='services/videos/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='services/videos/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='services.service')),
            ],
        ),
    ]
