# Generated by Django 6.0.3 on 2026-04-27 14:21

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_provider_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicegalleryimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicevideo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_type', 'is_active'], name='services_se_service_0e1319_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', '-created_at'], name='services_se_categor_588a33_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_featured', 'is_active'], name='services_se_is_feat_fb2165_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['rating'], name='services_se_rating_35e83b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['user', '-created_at'], name='services_se_user_id_cea692_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['service', '-created_at'], name='services_se_service_f49bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebooking',
            index=models.Index(fields=['status', 'booking_date'], name='services_se_status_6af1df_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecategory',
            index=models.Index(fields=['is_active', 'order'], name='services_se_is_acti_32bf00_idx'),
        ),
        migrations.AddIndex(
            model_name='servicegalleryimage',
            index=models.Index(fields=['service', 'order'], name='services_se_service_1e4289_idx'),
        ),
        migrations.AddIndex(
            model_name='servicegalleryimage',
            index=models.Index(fields=['is_main'], name='services_se_is_main_6b11a7_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereview',
            index=models.Index(fields=['service', '-created_at'], name='services_se_service_62d61a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereview',
            index=models.Index(fields=['rating'], name='services_se_rating_c531bd_idx'),
        ),
    ]
