# Generated by Django 6.0.3 on 2026-04-06 17:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('user_preferences', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('system', 'System')], default='user', max_length=10)),
                ('intent', models.CharField(blank=True, choices=[('property_search', 'Property Search'), ('booking', 'Booking'), ('services', 'Services'), ('price_inquiry', 'Price Inquiry'), ('location_inquiry', 'Location Inquiry'), ('favorites', 'Favorites'), ('greeting', 'Greeting'), ('help', 'Help'), ('general', 'General')], max_length=50, null=True)),
                ('content', models.TextField()),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('property_data', models.JSONField(blank=True, null=True)),
                ('service_data', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('intent', models.CharField(max_length=50)),
                ('response_time_ms', models.IntegerField()),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='UserChatPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_locations', models.JSONField(default=list)),
                ('preferred_property_types', models.JSONField(default=list)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('preferred_bedrooms', models.IntegerField(blank=True, null=True)),
                ('frequent_intents', models.JSONField(default=dict)),
                ('average_message_length', models.FloatField(default=0)),
                ('total_interactions', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_id'], name='chatbot_cha_session_9384e5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', '-updated_at'], name='chatbot_cha_user_id_52c956_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', '-created_at'], name='chatbot_cha_session_f839ac_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['intent'], name='chatbot_cha_intent_8c32aa_idx'),
        ),
    ]
