# Generated by Django 6.0.3 on 2026-04-06 17:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversationanalytics_userchatpreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
