# Generated by Django 6.0.3 on 2026-04-27 14:06

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        ('properties', '0027_alter_property_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='favorites_f_user_id_3c3f17_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['property', '-created_at'], name='favorites_f_propert_9f931a_idx'),
        ),
    ]
