# Generated by Django 6.0.3 on 2026-04-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_status_statusview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
