# Generated by Django 6.0.3 on 2026-04-27 11:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_status_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='status_media'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover_photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='verification_document'),
        ),
    ]
